import { createClient, SupabaseClient } from '@supabase/supabase-js';

// Default values from environment variables
export const DEFAULT_SUPABASE_URL = (import.meta.env.VITE_SUPABASE_URL || 'https://rlifyzffbybzfyuspllo.supabase.co').trim();
export const DEFAULT_SUPABASE_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsaWZ5emZmYnliemZ5dXNwbGxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAxODIzOTUsImV4cCI6MjEwNTc1ODM5NX0.FvkHjyfPtYWHOgp8S-6w4XHPSHhKLRpHL1JaQtE24J8').trim();

export function sanitizeSupabaseUrl(rawUrl: string): string {
  if (!rawUrl) return '';
  let url = rawUrl.trim();
  // Strip trailing /rest/v1 or /rest/v1/
  url = url.replace(/\/rest\/v1\/?$/, '');
  // Strip trailing slash
  url = url.replace(/\/+$/, '');
  return url;
}

export function extractProjectRef(url: string): string {
  try {
    const clean = sanitizeSupabaseUrl(url);
    const parsed = new URL(clean);
    const parts = parsed.hostname.split('.');
    return parts[0] || 'supabase-project';
  } catch {
    return 'supabase-project';
  }
}

// Stored credentials management
const STORAGE_KEY_URL = 'sb_custom_url';
const STORAGE_KEY_ANON = 'sb_custom_anon';

export function getActiveCredentials(): { url: string; anonKey: string; isCustom: boolean } {
  const customUrl = localStorage.getItem(STORAGE_KEY_URL);
  const customKey = localStorage.getItem(STORAGE_KEY_ANON);

  if (customUrl && customKey) {
    return {
      url: sanitizeSupabaseUrl(customUrl),
      anonKey: customKey.trim(),
      isCustom: true,
    };
  }

  return {
    url: sanitizeSupabaseUrl(DEFAULT_SUPABASE_URL),
    anonKey: DEFAULT_SUPABASE_KEY,
    isCustom: false,
  };
}

export function setCustomCredentials(url: string, anonKey: string) {
  localStorage.setItem(STORAGE_KEY_URL, sanitizeSupabaseUrl(url));
  localStorage.setItem(STORAGE_KEY_ANON, anonKey.trim());
  reinitClient();
}

export function resetCredentials() {
  localStorage.removeItem(STORAGE_KEY_URL);
  localStorage.removeItem(STORAGE_KEY_ANON);
  reinitClient();
}

// Singleton client instance
let supabaseInstance: SupabaseClient = createClient(
  getActiveCredentials().url,
  getActiveCredentials().anonKey
);

export function reinitClient(): SupabaseClient {
  const creds = getActiveCredentials();
  supabaseInstance = createClient(creds.url, creds.anonKey);
  return supabaseInstance;
}

export function getSupabase(): SupabaseClient {
  return supabaseInstance;
}

export async function checkConnectionHealth(): Promise<{
  connected: boolean;
  latencyMs: number;
  error?: string;
  sessionActive: boolean;
}> {
  const start = performance.now();
  try {
    const client = getSupabase();
    const { data, error } = await client.auth.getSession();
    const latency = Math.round(performance.now() - start);

    if (error) {
      return {
        connected: false,
        latencyMs: latency,
        error: error.message,
        sessionActive: false,
      };
    }

    return {
      connected: true,
      latencyMs: latency,
      sessionActive: !!data.session,
    };
  } catch (err: any) {
    return {
      connected: false,
      latencyMs: Math.round(performance.now() - start),
      error: err?.message || 'Connection failed',
      sessionActive: false,
    };
  }
}

// Preset SQL snippets for the user to execute in Supabase SQL editor
export const SQL_PRESETS = [
  {
    id: 'tasks',
    name: 'Tasks & Projects Schema',
    description: 'Creates a robust tasks table with status, priority, category, and due date.',
    tableName: 'tasks',
    sql: `-- 1. Create the tasks table
CREATE TABLE IF NOT EXISTS public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'todo' CHECK (status IN ('todo', 'in_progress', 'completed')),
  priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high')),
  category TEXT DEFAULT 'General',
  due_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

-- 3. Allow public read/write access (for development/demo)
CREATE POLICY "Allow public all access on tasks" 
  ON public.tasks 
  FOR ALL 
  TO anon, authenticated 
  USING (true) 
  WITH CHECK (true);

-- 4. Insert sample data
INSERT INTO public.tasks (title, description, status, priority, category)
VALUES
  ('Set up Supabase database', 'Connect project and run SQL migrations in Supabase Studio', 'completed', 'high', 'Setup'),
  ('Build live database dashboard', 'Create table view, CRUD operations, and real-time sync', 'in_progress', 'high', 'Frontend'),
  ('Configure Row Level Security (RLS)', 'Set granular authentication and access policies', 'todo', 'medium', 'Security'),
  ('Deploy application to production', 'Verify production build and share app URL', 'todo', 'low', 'DevOps');`
  },
  {
    id: 'notes',
    name: 'Quick Notes & Knowledge Base',
    description: 'Creates a notes table with title, content, category, and pinned status.',
    tableName: 'notes',
    sql: `-- 1. Create the notes table
CREATE TABLE IF NOT EXISTS public.notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  category TEXT DEFAULT 'General',
  is_pinned BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;

-- 3. Allow public read/write access
CREATE POLICY "Allow public all access on notes" 
  ON public.notes 
  FOR ALL 
  TO anon, authenticated 
  USING (true) 
  WITH CHECK (true);

-- 4. Insert sample data
INSERT INTO public.notes (title, content, category, is_pinned)
VALUES
  ('Supabase Architecture', 'Supabase gives you a dedicated PostgreSQL database with instant RESTful APIs, Auth, Realtime websockets, and Storage.', 'Tech', true),
  ('PostgreSQL Capabilities', 'Supports rich indexing, foreign keys, JSONB columns, stored procedures, and triggers right out of the box.', 'Database', false),
  ('API Best Practices', 'Use Row Level Security (RLS) policies to keep user data private and secure.', 'Security', false);`
  },
  {
    id: 'items',
    name: 'Universal Inventory / Items',
    description: 'Generic items catalog with price, quantity, and metadata.',
    tableName: 'items',
    sql: `-- 1. Create the items table
CREATE TABLE IF NOT EXISTS public.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  sku TEXT UNIQUE,
  price NUMERIC(10, 2) DEFAULT 0.00,
  quantity INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;

-- 3. Allow public read/write access
CREATE POLICY "Allow public all access on items" 
  ON public.items 
  FOR ALL 
  TO anon, authenticated 
  USING (true) 
  WITH CHECK (true);

-- 4. Insert sample items
INSERT INTO public.items (name, sku, price, quantity)
VALUES
  ('Pro Developer Subscription', 'SUB-PRO-01', 29.00, 100),
  ('Database Storage 10GB Addon', 'STOR-10GB', 10.00, 500),
  ('Custom Domain SSL Certificate', 'SEC-SSL-01', 15.00, 250);`
  }
];
